services:
  next_social_app:
    container_name: next_social_app
    image: next_social_image
    build: .
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@next_social_db:${POSTGRES_PORT}/${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "3000:3000"
    depends_on:
      next_social_db:
        condition: service_healthy
    
  next_social_db:
    image: postgres:17
    container_name: next_social_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - nextjs_social_app:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
volumes:
  nextjs_social_app: